import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
import { Roboto } from "next/font/google";
import favicon from '@/app/favicon.png'

const inter = Inter({ subsets: ['latin'] })
const robotoFont = Roboto({
  //Fuente de google fonts configuracion
  weight: ["300"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: 'VenSalud - Proyecto de pasantias',
  description: 'Generated by create next app',
  icons: {
    icon: `${favicon.src}`
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={`${inter.className} flex ${robotoFont.className}  
      flex flex-col md:flex-row h-screen overflow-hidden`}>
        <Sidebar />
        <div className={`flex-1 bg-gray-200 overflow-y-auto`}>
          <Navbar />
          {children}
        </div>

      </body>
    </html>
  )
}
