import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar' // Importa el Sidebar

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VenSalud',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen`}>
        <Sidebar />
        <div className={`flex-1 bg-gray-200`}>
          <Navbar />
          {children}
        </div>

      </body>
    </html>
  )
}
